-- ###################################################
-- # H2 database setup for Spring Boot example
-- ###################################################

-- 'customer' data
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Aja', 'Miller',	24, 'Keimfarben');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Abb', 'Miller',	24, 'Air Berlin');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Abe', 'Garcia',	25, 'Auto Union');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ace', 'Wilson',	26, 'Beiersdorf');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Acy', 'Taylor',	27, 'Blohm+Voss');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ada', 'Thomas',	28, 'Büssing AG');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Add', 'Martin',	29, 'Daimler AG');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Aja', 'Harris',	30, 'Dr. Oetker');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ala', 'Walker',	31, 'Ferrostaal');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Alf', 'Wright',	32, 'Focke-Wulf');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ali', 'Nelson',	33, 'Freenet.de');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ama', 'Carter',	34, 'Hama Photo');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ami', 'Turner',	35, 'J. Schmalz');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Amy', 'Torres',	36, 'Jil Sander');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ana', 'Parker',	37, 'Keimfarben');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ann', 'Flores',	38, 'Mahle GmbH');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ara', 'Morris',	39, 'Mannesmann');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ari', 'Nguyen',	40, 'Nemetschek');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Art', 'Murphy',	24, 'Nordzucker');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Asa', 'Rivera',	25, 'REWE Group');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ava', 'Rogers',	26, 'ROSE Bikes');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Bea', 'Morgan',	27, 'Sennheiser');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Bee', 'Cooper',	28, 'SGL Carbon');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ben', 'Bailey',	29, 'SolarWorld');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Bev', 'Howard',	30, 'Telefunken');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Bob', 'Watson',	31, 'Volkswagen');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Bud', 'Brooks',	32, 'Warsteiner');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Cal', 'Hughes',	33, 'Air Berlin');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Cam', 'Foster',	34, 'Auto Union');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Cap', 'Powell',	35, 'Beiersdorf');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Cas', 'Butler',	36, 'Blohm+Voss');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Che', 'Barnes',	37, 'Büssing AG');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Con', 'Fisher',	38, 'Daimler AG');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Coy', 'Jordan',	39, 'Dr. Oetker');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Dan', 'Graham',	40, 'Ferrostaal');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Dax', 'Chavez',	24, 'Focke-Wulf');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Deb', 'Gibson',	25, 'Freenet.de');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Dee', 'Bryant',	26, 'Hama Photo');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Del', 'Murray',	27, 'J. Schmalz');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Doc', 'Tucker',	28, 'Jil Sander');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Don', 'Snyder',	29, 'Keimfarben');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Dot', 'Porter',	30, 'Mahle GmbH');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Dow', 'Gordon',	31, 'Mannesmann');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ean', 'Wagner',	32, 'Nemetschek');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ebb', 'Hunter',	33, 'Nordzucker');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Eda', 'Romero',	34, 'REWE Group');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Edd', 'Palmer',	35, 'ROSE Bikes');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Edw', 'Holmes',	36, 'Sennheiser');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ela', 'Warren',	37, 'SGL Carbon');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Eli', 'Moreno',	38, 'SolarWorld');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ell', 'Medina',	39, 'Telefunken');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ely', 'Weaver',	40, 'Volkswagen');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ema', 'Kelley',	24, 'Warsteiner');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ena', 'Pierce',	25, 'Air Berlin');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Era', 'Arnold',	26, 'Auto Union');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Eva', 'Peters',	27, 'Beiersdorf');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Eve', 'Hansen',	28, 'Blohm+Voss');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Exa', 'Castro',	29, 'Büssing AG');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Fae', 'Knight',	30, 'Daimler AG');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Fay', 'Hudson',	31, 'Dr. Oetker');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Fed', 'Duncan',	32, 'Ferrostaal');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Flo', 'Willis',	33, 'Focke-Wulf');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Foy', 'Vargas',	34, 'Freenet.de');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Gay', 'Larson',	35, 'Hama Photo');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Gee', 'Harper',	36, 'J. Schmalz');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Geo', 'George',	37, 'Jil Sander');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Gia', 'Greene',	38, 'Keimfarben');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Gil', 'Guzman',	39, 'Mahle GmbH');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Gus', 'Jacobs',	40, 'Mannesmann');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Guy', 'Obrien',	24, 'Nemetschek');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Hal', 'Lawson',	25, 'Nordzucker');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ham', 'Bishop',	26, 'REWE Group');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Hoy', 'Austin',	27, 'ROSE Bikes');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Huy', 'Mendez',	28, 'Sennheiser');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ian', 'Jensen',	29, 'SGL Carbon');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ica', 'Harvey',	30, 'SolarWorld');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Icy', 'Oliver',	31, 'Telefunken');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ida', 'Howell',	32, 'Volkswagen');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ike', 'Hanson',	33, 'Warsteiner');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ila', 'Burton',	34, 'Air Berlin');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ilo', 'Fuller',	35, 'Auto Union');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ima', 'Fields',	36, 'Beiersdorf');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Imo', 'Little',	37, 'Blohm+Voss');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ina', 'Fowler',	38, 'Büssing AG');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ira', 'Bowman',	39, 'Daimler AG');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Irl', 'Newman',	40, 'Dr. Oetker');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Isa', 'Brewer',	24, 'Ferrostaal');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Iva', 'Santos',	25, 'Focke-Wulf');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ivy', 'Curtis',	26, 'Freenet.de');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Iza', 'Valdez',	27, 'Hama Photo');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Jan', 'Keller',	28, 'J. Schmalz');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Jax', 'Ortega',	29, 'Jil Sander');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Jay', 'Powers',	30, 'Keimfarben');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Jeb', 'Rhodes',	31, 'Mahle GmbH');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Jed', 'Becker',	32, 'Mannesmann');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Jep', 'Sutton',	33, 'Nemetschek');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Jim', 'Barker',	34, 'Nordzucker');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Job', 'Norris',	35, 'REWE Group');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Joe', 'Vaughn',	36, 'ROSE Bikes');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Joi', 'Steele',	37, 'Sennheiser');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Jon', 'Benson',	38, 'SGL Carbon');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Joy', 'Horton',	39, 'SolarWorld');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Kai', 'Graves',	40, 'Telefunken');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Kay', 'Haynes',	24, 'Volkswagen');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Kem', 'Warner',	25, 'Warsteiner');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ken', 'Dawson',	26, 'Air Berlin');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Kia', 'Joseph',	27, 'Auto Union');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Kim', 'Reeves',	28, 'Beiersdorf');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Kip', 'Cortez',	29, 'Blohm+Voss');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Kit', 'Ramsey',	30, 'Büssing AG');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Kya', 'Barber',	31, 'Daimler AG');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Lea', 'Acosta',	32, 'Dr. Oetker');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Lee', 'Daniel',	33, 'Ferrostaal');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Lem', 'Dennis',	34, 'Focke-Wulf');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Len', 'Harmon',	35, 'Freenet.de');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Leo', 'Newton',	36, 'Hama Photo');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Les', 'Garner',	37, 'J. Schmalz');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Lew', 'Adkins',	38, 'Jil Sander');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Lex', 'Potter',	39, 'Keimfarben');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Lia', 'Walton',	40, 'Mahle GmbH');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Lim', 'Molina',	24, 'Mannesmann');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Liz', 'Campos',	25, 'Nemetschek');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Lon', 'Malone',	26, 'Nordzucker');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Lou', 'Hodges',	27, 'REWE Group');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Loy', 'Juarez',	28, 'ROSE Bikes');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Luc', 'Farmer',	29, 'Sennheiser');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Lue', 'Cannon',	30, 'SGL Carbon');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Lum', 'Ingram',	31, 'SolarWorld');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Luz', 'Barton',	32, 'Telefunken');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Lyn', 'Waters',	33, 'Volkswagen');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Mac', 'Deleon',	34, 'Warsteiner');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Mae', 'Norman',	35, 'Air Berlin');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Mai', 'Patton',	36, 'Auto Union');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Mal', 'Bowers',	37, 'Beiersdorf');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Mat', 'Glover',	38, 'Blohm+Voss');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Max', 'French',	39, 'Büssing AG');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'May', 'Kramer',	40, 'Daimler AG');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Meg', 'Clarke',	24, 'Dr. Oetker');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Mel', 'Conner',	25, 'Ferrostaal');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Mia', 'Sparks',	26, 'Focke-Wulf');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Moe', 'Norton',	27, 'Freenet.de');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Mya', 'Robles',	28, 'Hama Photo');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Nan', 'Morton',	29, 'J. Schmalz');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Nat', 'Stokes',	30, 'Jil Sander');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ned', 'Briggs',	31, 'Keimfarben');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Nia', 'Meyers',	32, 'Mahle GmbH');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Nim', 'Hoover',	33, 'Mannesmann');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Noe', 'Carson',	34, 'Nemetschek');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Nya', 'Morrow',	35, 'Nordzucker');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Obe', 'Wilcox',	36, 'REWE Group');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Oda', 'Guerra',	37, 'ROSE Bikes');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ola', 'Decker',	38, 'Sennheiser');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ole', 'Conley',	39, 'SGL Carbon');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Oma', 'Monroe',	40, 'SolarWorld');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ona', 'Massey',	24, 'Telefunken');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ora', 'Franco',	25, 'Volkswagen');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Osa', 'Larsen',	26, 'Warsteiner');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ota', 'Mathis',	27, 'Air Berlin');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ott', 'Abbott',	28, 'Auto Union');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ova', 'Phelps',	29, 'Beiersdorf');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Pam', 'Dalton',	30, 'Blohm+Voss');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Pat', 'Atkins',	31, 'Büssing AG');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Rae', 'Grimes',	32, 'Daimler AG');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ras', 'Dillon',	33, 'Dr. Oetker');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ray', 'Oneill',	34, 'Ferrostaal');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Red', 'Melton',	35, 'Focke-Wulf');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Rex', 'Savage',	36, 'Freenet.de');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Rey', 'Sawyer',	37, 'Hama Photo');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Rob', 'Baxter',	38, 'J. Schmalz');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Rod', 'Golden',	39, 'Jil Sander');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Roe', 'Walter',	40, 'Keimfarben');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ron', 'Suarez',	24, 'Mahle GmbH');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Roy', 'Ibarra',	25, 'Mannesmann');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Sal', 'Macias',	26, 'Nemetschek');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Sam', 'Henson',	27, 'Nordzucker');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Sid', 'Tanner',	28, 'REWE Group');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Sie', 'Barron',	29, 'ROSE Bikes');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Sim', 'Zamora',	30, 'Sennheiser');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Sky', 'Orozco',	31, 'SGL Carbon');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Sol', 'Mosley',	32, 'SolarWorld');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Son', 'Prince',	33, 'Telefunken');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Sue', 'Lester',	34, 'Volkswagen');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Tab', 'Berger',	35, 'Warsteiner');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Tad', 'Strong',	36, 'Air Berlin');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Tai', 'Conway',	37, 'Auto Union');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Taj', 'Lozano',	38, 'Beiersdorf');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Tal', 'Pruitt',	39, 'Blohm+Voss');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Tea', 'Gaines',	40, 'Büssing AG');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ted', 'Durham',	24, 'Daimler AG');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Tex', 'Gentry',	25, 'Dr. Oetker');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Tia', 'Herman',	26, 'Ferrostaal');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Tim', 'Sexton',	27, 'Focke-Wulf');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Tod', 'Rangel',	28, 'Freenet.de');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Tom', 'Lowery',	29, 'Hama Photo');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Toy', 'Hardin',	30, 'J. Schmalz');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Tre', 'Mccall',	31, 'Jil Sander');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Tye', 'Dorsey',	32, 'Keimfarben');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ula', 'Mclean',	33, 'Mahle GmbH');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Una', 'Reilly',	34, 'Mannesmann');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Ura', 'Hebert',	35, 'Nemetschek');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Val', 'Spears',	36, 'Nordzucker');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Van', 'Conrad',	37, 'REWE Group');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Vic', 'Galvan',	38, 'ROSE Bikes');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Von', 'Zuniga',	39, 'Sennheiser');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Wes', 'Pineda',	40, 'SGL Carbon');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Yee', 'Hurley',	24, 'SolarWorld');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Zeb', 'Crosby',	25, 'Telefunken');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Zed', 'Dunlap',	26, 'Volkswagen');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Zoa', 'Bender',	27, 'Warsteiner');
insert into customer(id, first_name, last_name, age, company) values(nextval('customer_sequence'), 'Zoe', 'Landry',	28, 'Air Berlin');

--
-- 'company' data
insert into company(id, name) values(nextval('company_sequence'), 'ALLTEL Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'Ameren Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'Apache Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'ArvinMeritor, Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Avista Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'Best Buy Co., Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'BMC Software, Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Budget Group, Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Carlisle Cos. Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Cisco Systems Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'ConAgra Foods Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Dean Foods Company');
insert into company(id, name) values(nextval('company_sequence'), 'Del Monte Foods Co');
insert into company(id, name) values(nextval('company_sequence'), 'Deluxe Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'Domingos Pizza LLC');
insert into company(id, name) values(nextval('company_sequence'), 'Exelon Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'Exide Technologies');
insert into company(id, name) values(nextval('company_sequence'), 'Flowers Foods Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'General Mills Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'H.J. Heinz Company');
insert into company(id, name) values(nextval('company_sequence'), 'Herman Miller Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Hormel Foods Corp.');
insert into company(id, name) values(nextval('company_sequence'), 'Hughes Supply Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Ingles Market Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Jabil Circuit Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'JDS Uniphase Corp.');
insert into company(id, name) values(nextval('company_sequence'), 'Knight-Ridder Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Lennar Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'Levi Strauss & Co.');
insert into company(id, name) values(nextval('company_sequence'), 'Lithia Motors Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Liz Claiborne Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Markel Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'Maxtor Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'Maytag Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'Mirant Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'Oshkosh Truck Corp');
insert into company(id, name) values(nextval('company_sequence'), 'Owens & Minor Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'PepsiAmericas Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Perot Systems Corp');
insert into company(id, name) values(nextval('company_sequence'), 'Phelps Dodge Corp.');
insert into company(id, name) values(nextval('company_sequence'), 'PNM Resources Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Rent A Center Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Sears Roebuck & Co');
insert into company(id, name) values(nextval('company_sequence'), 'Shopko Stores Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Southwest Gas Corp');
insert into company(id, name) values(nextval('company_sequence'), 'Staff Leasing Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'State Street Corp.');
insert into company(id, name) values(nextval('company_sequence'), 'Temple-Inland Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'The Boeing Company');
insert into company(id, name) values(nextval('company_sequence'), 'TJX Companies Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'TMP Worldwide Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Toll Brothers Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Unisys Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'Unocal Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'W.W. Grainger Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Yellow Corporation');
