-- ###################################################
-- # H2 database setup for Spring Boot example
-- ###################################################

-- 'customer' data
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Abb', 'Miller', 'Air Berlin');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Abe', 'Garcia', 'Auto Union');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ace', 'Wilson', 'Beiersdorf');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Acy', 'Taylor', 'Blohm+Voss');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ada', 'Thomas', 'Büssing AG');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Add', 'Martin', 'Daimler AG');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Aja', 'Harris', 'Dr. Oetker');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ala', 'Walker', 'Ferrostaal');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Alf', 'Wright', 'Focke-Wulf');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ali', 'Nelson', 'Freenet.de');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ama', 'Carter', 'Hama Photo');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ami', 'Turner', 'J. Schmalz');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Amy', 'Torres', 'Jil Sander');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ana', 'Parker', 'Keimfarben');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ann', 'Flores', 'Mahle GmbH');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ara', 'Morris', 'Mannesmann');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ari', 'Nguyen', 'Nemetschek');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Art', 'Murphy', 'Nordzucker');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Asa', 'Rivera', 'REWE Group');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ava', 'Rogers', 'ROSE Bikes');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Bea', 'Morgan', 'Sennheiser');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Bee', 'Cooper', 'SGL Carbon');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ben', 'Bailey', 'SolarWorld');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Bev', 'Howard', 'Telefunken');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Bob', 'Watson', 'Volkswagen');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Bud', 'Brooks', 'Warsteiner');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Cal', 'Hughes', 'Air Berlin');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Cam', 'Foster', 'Auto Union');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Cap', 'Powell', 'Beiersdorf');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Cas', 'Butler', 'Blohm+Voss');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Che', 'Barnes', 'Büssing AG');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Con', 'Fisher', 'Daimler AG');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Coy', 'Jordan', 'Dr. Oetker');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Dan', 'Graham', 'Ferrostaal');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Dax', 'Chavez', 'Focke-Wulf');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Deb', 'Gibson', 'Freenet.de');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Dee', 'Bryant', 'Hama Photo');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Del', 'Murray', 'J. Schmalz');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Doc', 'Tucker', 'Jil Sander');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Don', 'Snyder', 'Keimfarben');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Dot', 'Porter', 'Mahle GmbH');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Dow', 'Gordon', 'Mannesmann');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ean', 'Wagner', 'Nemetschek');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ebb', 'Hunter', 'Nordzucker');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Eda', 'Romero', 'REWE Group');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Edd', 'Palmer', 'ROSE Bikes');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Edw', 'Holmes', 'Sennheiser');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ela', 'Warren', 'SGL Carbon');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Eli', 'Moreno', 'SolarWorld');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ell', 'Medina', 'Telefunken');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ely', 'Weaver', 'Volkswagen');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ema', 'Kelley', 'Warsteiner');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ena', 'Pierce', 'Air Berlin');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Era', 'Arnold', 'Auto Union');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Eva', 'Peters', 'Beiersdorf');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Eve', 'Hansen', 'Blohm+Voss');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Exa', 'Castro', 'Büssing AG');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Fae', 'Knight', 'Daimler AG');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Fay', 'Hudson', 'Dr. Oetker');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Fed', 'Duncan', 'Ferrostaal');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Flo', 'Willis', 'Focke-Wulf');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Foy', 'Vargas', 'Freenet.de');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Gay', 'Larson', 'Hama Photo');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Gee', 'Harper', 'J. Schmalz');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Geo', 'George', 'Jil Sander');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Gia', 'Greene', 'Keimfarben');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Gil', 'Guzman', 'Mahle GmbH');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Gus', 'Jacobs', 'Mannesmann');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Guy', 'Obrien', 'Nemetschek');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Hal', 'Lawson', 'Nordzucker');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ham', 'Bishop', 'REWE Group');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Hoy', 'Austin', 'ROSE Bikes');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Huy', 'Mendez', 'Sennheiser');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ian', 'Jensen', 'SGL Carbon');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ica', 'Harvey', 'SolarWorld');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Icy', 'Oliver', 'Telefunken');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ida', 'Howell', 'Volkswagen');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ike', 'Hanson', 'Warsteiner');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ila', 'Burton', 'Air Berlin');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ilo', 'Fuller', 'Auto Union');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ima', 'Fields', 'Beiersdorf');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Imo', 'Little', 'Blohm+Voss');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ina', 'Fowler', 'Büssing AG');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ira', 'Bowman', 'Daimler AG');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Irl', 'Newman', 'Dr. Oetker');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Isa', 'Brewer', 'Ferrostaal');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Iva', 'Santos', 'Focke-Wulf');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ivy', 'Curtis', 'Freenet.de');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Iza', 'Valdez', 'Hama Photo');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Jan', 'Keller', 'J. Schmalz');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Jax', 'Ortega', 'Jil Sander');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Jay', 'Powers', 'Keimfarben');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Jeb', 'Rhodes', 'Mahle GmbH');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Jed', 'Becker', 'Mannesmann');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Jep', 'Sutton', 'Nemetschek');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Jim', 'Barker', 'Nordzucker');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Job', 'Norris', 'REWE Group');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Joe', 'Vaughn', 'ROSE Bikes');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Joi', 'Steele', 'Sennheiser');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Jon', 'Benson', 'SGL Carbon');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Joy', 'Horton', 'SolarWorld');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Kai', 'Graves', 'Telefunken');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Kay', 'Haynes', 'Volkswagen');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Kem', 'Warner', 'Warsteiner');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ken', 'Dawson', 'Air Berlin');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Kia', 'Joseph', 'Auto Union');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Kim', 'Reeves', 'Beiersdorf');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Kip', 'Cortez', 'Blohm+Voss');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Kit', 'Ramsey', 'Büssing AG');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Kya', 'Barber', 'Daimler AG');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Lea', 'Acosta', 'Dr. Oetker');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Lee', 'Daniel', 'Ferrostaal');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Lem', 'Dennis', 'Focke-Wulf');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Len', 'Harmon', 'Freenet.de');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Leo', 'Newton', 'Hama Photo');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Les', 'Garner', 'J. Schmalz');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Lew', 'Adkins', 'Jil Sander');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Lex', 'Potter', 'Keimfarben');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Lia', 'Walton', 'Mahle GmbH');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Lim', 'Molina', 'Mannesmann');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Liz', 'Campos', 'Nemetschek');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Lon', 'Malone', 'Nordzucker');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Lou', 'Hodges', 'REWE Group');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Loy', 'Juarez', 'ROSE Bikes');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Luc', 'Farmer', 'Sennheiser');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Lue', 'Cannon', 'SGL Carbon');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Lum', 'Ingram', 'SolarWorld');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Luz', 'Barton', 'Telefunken');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Lyn', 'Waters', 'Volkswagen');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Mac', 'Deleon', 'Warsteiner');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Mae', 'Norman', 'Air Berlin');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Mai', 'Patton', 'Auto Union');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Mal', 'Bowers', 'Beiersdorf');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Mat', 'Glover', 'Blohm+Voss');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Max', 'French', 'Büssing AG');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'May', 'Kramer', 'Daimler AG');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Meg', 'Clarke', 'Dr. Oetker');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Mel', 'Conner', 'Ferrostaal');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Mia', 'Sparks', 'Focke-Wulf');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Moe', 'Norton', 'Freenet.de');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Mya', 'Robles', 'Hama Photo');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Nan', 'Morton', 'J. Schmalz');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Nat', 'Stokes', 'Jil Sander');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ned', 'Briggs', 'Keimfarben');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Nia', 'Meyers', 'Mahle GmbH');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Nim', 'Hoover', 'Mannesmann');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Noe', 'Carson', 'Nemetschek');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Nya', 'Morrow', 'Nordzucker');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Obe', 'Wilcox', 'REWE Group');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Oda', 'Guerra', 'ROSE Bikes');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ola', 'Decker', 'Sennheiser');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ole', 'Conley', 'SGL Carbon');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Oma', 'Monroe', 'SolarWorld');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ona', 'Massey', 'Telefunken');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ora', 'Franco', 'Volkswagen');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Osa', 'Larsen', 'Warsteiner');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ota', 'Mathis', 'Air Berlin');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ott', 'Abbott', 'Auto Union');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ova', 'Phelps', 'Beiersdorf');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Pam', 'Dalton', 'Blohm+Voss');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Pat', 'Atkins', 'Büssing AG');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Rae', 'Grimes', 'Daimler AG');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ras', 'Dillon', 'Dr. Oetker');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ray', 'Oneill', 'Ferrostaal');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Red', 'Melton', 'Focke-Wulf');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Rex', 'Savage', 'Freenet.de');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Rey', 'Sawyer', 'Hama Photo');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Rob', 'Baxter', 'J. Schmalz');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Rod', 'Golden', 'Jil Sander');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Roe', 'Walter', 'Keimfarben');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ron', 'Suarez', 'Mahle GmbH');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Roy', 'Ibarra', 'Mannesmann');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Sal', 'Macias', 'Nemetschek');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Sam', 'Henson', 'Nordzucker');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Sid', 'Tanner', 'REWE Group');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Sie', 'Barron', 'ROSE Bikes');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Sim', 'Zamora', 'Sennheiser');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Sky', 'Orozco', 'SGL Carbon');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Sol', 'Mosley', 'SolarWorld');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Son', 'Prince', 'Telefunken');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Sue', 'Lester', 'Volkswagen');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Tab', 'Berger', 'Warsteiner');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Tad', 'Strong', 'Air Berlin');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Tai', 'Conway', 'Auto Union');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Taj', 'Lozano', 'Beiersdorf');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Tal', 'Pruitt', 'Blohm+Voss');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Tea', 'Gaines', 'Büssing AG');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ted', 'Durham', 'Daimler AG');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Tex', 'Gentry', 'Dr. Oetker');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Tia', 'Herman', 'Ferrostaal');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Tim', 'Sexton', 'Focke-Wulf');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Tod', 'Rangel', 'Freenet.de');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Tom', 'Lowery', 'Hama Photo');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Toy', 'Hardin', 'J. Schmalz');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Tre', 'Mccall', 'Jil Sander');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Tye', 'Dorsey', 'Keimfarben');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ula', 'Mclean', 'Mahle GmbH');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Una', 'Reilly', 'Mannesmann');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Ura', 'Hebert', 'Nemetschek');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Val', 'Spears', 'Nordzucker');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Van', 'Conrad', 'REWE Group');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Vic', 'Galvan', 'ROSE Bikes');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Von', 'Zuniga', 'Sennheiser');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Wes', 'Pineda', 'SGL Carbon');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Yee', 'Hurley', 'SolarWorld');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Zeb', 'Crosby', 'Telefunken');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Zed', 'Dunlap', 'Volkswagen');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Zoa', 'Bender', 'Warsteiner');
insert into customer(id, first_name, last_name, company) values(nextval('customer_sequence'), 'Zoe', 'Landry', 'Air Berlin');

--
-- 'company' data
insert into company(id, name) values(nextval('company_sequence'), 'ALLTEL Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'Ameren Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'Apache Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'ArvinMeritor, Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Avista Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'Best Buy Co., Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'BMC Software, Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Budget Group, Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Carlisle Cos. Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Cisco Systems Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'ConAgra Foods Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Dean Foods Company');
insert into company(id, name) values(nextval('company_sequence'), 'Del Monte Foods Co');
insert into company(id, name) values(nextval('company_sequence'), 'Deluxe Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'Domingos Pizza LLC');
insert into company(id, name) values(nextval('company_sequence'), 'Exelon Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'Exide Technologies');
insert into company(id, name) values(nextval('company_sequence'), 'Flowers Foods Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'General Mills Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'H.J. Heinz Company');
insert into company(id, name) values(nextval('company_sequence'), 'Herman Miller Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Hormel Foods Corp.');
insert into company(id, name) values(nextval('company_sequence'), 'Hughes Supply Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Ingles Market Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Jabil Circuit Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'JDS Uniphase Corp.');
insert into company(id, name) values(nextval('company_sequence'), 'Knight-Ridder Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Lennar Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'Levi Strauss & Co.');
insert into company(id, name) values(nextval('company_sequence'), 'Lithia Motors Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Liz Claiborne Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Markel Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'Maxtor Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'Maytag Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'Mirant Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'Oshkosh Truck Corp');
insert into company(id, name) values(nextval('company_sequence'), 'Owens & Minor Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'PepsiAmericas Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Perot Systems Corp');
insert into company(id, name) values(nextval('company_sequence'), 'Phelps Dodge Corp.');
insert into company(id, name) values(nextval('company_sequence'), 'PNM Resources Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Rent A Center Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Sears Roebuck & Co');
insert into company(id, name) values(nextval('company_sequence'), 'Shopko Stores Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Southwest Gas Corp');
insert into company(id, name) values(nextval('company_sequence'), 'Staff Leasing Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'State Street Corp.');
insert into company(id, name) values(nextval('company_sequence'), 'Temple-Inland Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'The Boeing Company');
insert into company(id, name) values(nextval('company_sequence'), 'TJX Companies Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'TMP Worldwide Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Toll Brothers Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Unisys Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'Unocal Corporation');
insert into company(id, name) values(nextval('company_sequence'), 'W.W. Grainger Inc.');
insert into company(id, name) values(nextval('company_sequence'), 'Yellow Corporation');
